[package]
name = "volm"
version = "0.0.1"
edition = "2021"

[dependencies]
rayon = "1.5.1"
ultraviolet = { version = "0.9.0", git = "https://github.com/joe-loach/ultraviolet.git" }

[dev-dependencies]
image = "0.23"